### ISSUE TITLE
Add the support pnpm in the buildpack

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/nodejs-buildpack#60]
Add the support of pnpm to the buildpack: https://pnpm.io

For now we recommend to use the following Heroku community buildpack: https://github.com/unfold/heroku-buildpack-pnpm

A customer asked to have it: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/3379738/conversations/12375700071669

**Comment by EtienneM** [comment]
This buildpack mostly relies on Heroku buildpacks. A question has already been asked upstream for this change (https://github.com/heroku/heroku-buildpack-nodejs/issues/688#issuecomment-1032041105) and was reject.

I don't think we want to add more work here, so this will probably not be implemented on our side any time soon.

> For now we recommend to use the following Heroku community buildpack

I don't know which "we" you are referring to, but Scalingo has no official recommendation for community buildpack. There is always a risk to use a community buildpack and we don't officially recommend one over another.

**Comment by sneko** [comment]
I had hard time first trying to hack your node buildpack to use pnpm... but pure loss of time ^^...

I should have tried an Heroku buildpack. Even it's not a guaranteed by Scalingo, at least I have a working deployment without much hurdle. Here a list to try if wanted:
* https://github.com/unfold/heroku-buildpack-pnpm (most used, use `heroku-postbuild` instead of `scaligno-postbuild`)
*  https://github.com/TheSecurityDev/heroku-buildpack-nodejs-pnpm (same as above but allow installing `devDependencies`)
* https://github.com/c0urg3tt3/pnpm-buildpack (targetting Scalingo from scratch, but too many things harcoded so pretty complex to manage, except if you fork it)

For me, `pnpm` has proven to be a really good package manager. Having a note in the docs would not be too much... _(but still, the perfect fit would be to allow pushing Docker images, so developers focus on a standard and don't fight with extending buildpacks, and could make proper images of a few MB instead of big packages :D )_

**Comment by EtienneM** [comment]
For the record, upstream declined the addition of pnpm for now: https://github.com/heroku/heroku-buildpack-nodejs/issues/688

**Comment by sneko** [comment]
@EtienneM did you try it with success?

Scalingo buildpack is based on the Heroku one, and in their pnpm issues I did not see someone with a working solution except by using another buildpack.

**Comment by fdietz** [comment]
Hi everyone!

It seems that the official heroku nodejs buildpack will soonish support pnpm as a package manager.

Is it safe for us to use the heroku nodejs buildpack? We are unsure if this one (from scalingo) has any scalingo specific things which would break it.

Thanks in advance,
-Frederik
