### ISSUE TITLE
If engines.yarn is specified and engines.npm is unspecified, use yarn

### ISSUE THREAD

**Issue by jdauphant** [Scalingo/nodejs-buildpack#97]
**Is your enhancement request related to a problem? Please describe.**
Actually if there is no yarn.lock and no package-lock.json but engines.yarn is specified and engines.npm is unspecified, the buildpack use npm.

**Describe the solution you'd like**
If there is no yarn.lock, no package-lock.json but engines.yarn is specified and engines.npm is unspecified, the buildpack shoukd be yarn.

**Describe alternatives you've considered**
I maintain a fork of the project I new to deploy ( cal.com )

**Additional context**
https://github.com/calcom/cal.com don't use yarn.lock neither package-lock.json but require usage of yarn.

**Comment by ipfaze** [comment]
Hello Julien,
Thank you for your issue but as this buildpack is a fork of the Heroku one. I think your fix will have more positive impact if you open an issue on the Heroku repository rather than ours. 
Indeed when the fix will be done on it, all forks repositories will profit of it and ours too of course.

Here is the link to the issues table of the Heroku NodeJS buildpack: https://github.com/heroku/heroku-buildpack-nodejs/issues
